# Generated by Django 4.2.28 on 2026-03-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_alter_tweet_options_tweet_likes_tweet_parent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower'], name='tweet_follo_followe_4cfd9d_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following'], name='tweet_follo_followi_254a23_idx'),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['user'], name='tweet_tweet_user_id_c86374_idx'),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['created_at'], name='tweet_tweet_created_499a55_idx'),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['parent'], name='tweet_tweet_parent__0a091e_idx'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='unique_follow_relationship'),
        ),
    ]
