# Generated by Django 4.2.28 on 2026-03-16 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0004_alter_follow_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='retweets',
            field=models.ManyToManyField(blank=True, related_name='retweeted_tweets', to=settings.AUTH_USER_MODEL),
        ),
    ]
